// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as format$0 from "../internal/format/models.js";

/**
 * HotkeyConfig 单个快捷键配置
 */
export class HotkeyConfig {
    /**
     * Creates a new HotkeyConfig instance.
     * @param {Partial<HotkeyConfig>} [$$source = {}] - The source object to create the HotkeyConfig.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * 是否启用
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("keys" in $$source)) {
            /**
             * 组合键字符串，如 "Ctrl+Shift+P"
             * @member
             * @type {string}
             */
            this["keys"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HotkeyConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HotkeyConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HotkeyConfig(/** @type {Partial<HotkeyConfig>} */($$parsedSource));
    }
}

/**
 * I18nData 统一翻译数据结构（前后端共享）
 */
export class I18nData {
    /**
     * Creates a new I18nData instance.
     * @param {Partial<I18nData>} [$$source = {}] - The source object to create the I18nData.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["version"] = 0;
        }
        if (!("languages" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: { [_ in string]?: string } }}
             */
            this["languages"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new I18nData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {I18nData}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("languages" in $$parsedSource) {
            $$parsedSource["languages"] = $$createField1_0($$parsedSource["languages"]);
        }
        return new I18nData(/** @type {Partial<I18nData>} */($$parsedSource));
    }
}

/**
 * I18nMergeResult 合并执行结果
 */
export class I18nMergeResult {
    /**
     * Creates a new I18nMergeResult instance.
     * @param {Partial<I18nMergeResult>} [$$source = {}] - The source object to create the I18nMergeResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("message" in $$source)) {
            /**
             * 成功 / 失败提示（会走前端本地 i18n，这里只给英文兜底文案）
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new I18nMergeResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {I18nMergeResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new I18nMergeResult(/** @type {Partial<I18nMergeResult>} */($$parsedSource));
    }
}

/**
 * I18nNewKeysReport 返回给前端的差异报告
 */
export class I18nNewKeysReport {
    /**
     * Creates a new I18nNewKeysReport instance.
     * @param {Partial<I18nNewKeysReport>} [$$source = {}] - The source object to create the I18nNewKeysReport.
     */
    constructor($$source = {}) {
        if (!("has_new" in $$source)) {
            /**
             * 是否存在任何差异（新语言/新键/值变更/冗余键）
             * @member
             * @type {boolean}
             */
            this["has_new"] = false;
        }
        if (!("total_new" in $$source)) {
            /**
             * 新键总数（跨语言汇总）
             * @member
             * @type {number}
             */
            this["total_new"] = 0;
        }
        if (!("total_chg" in $$source)) {
            /**
             * 值变化键总数（跨语言汇总）
             * @member
             * @type {number}
             */
            this["total_chg"] = 0;
        }
        if (!("total_obsolete" in $$source)) {
            /**
             * 冗余键总数（跨语言汇总）
             * @member
             * @type {number}
             */
            this["total_obsolete"] = 0;
        }
        if (!("new_langs" in $$source)) {
            /**
             * 内嵌比用户多出来的语言代码
             * @member
             * @type {string[]}
             */
            this["new_langs"] = [];
        }
        if (!("diffs" in $$source)) {
            /**
             * 按语言分组的具体差异
             * @member
             * @type {LangKeyDiff[]}
             */
            this["diffs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new I18nNewKeysReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {I18nNewKeysReport}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType2;
        const $$createField5_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("new_langs" in $$parsedSource) {
            $$parsedSource["new_langs"] = $$createField4_0($$parsedSource["new_langs"]);
        }
        if ("diffs" in $$parsedSource) {
            $$parsedSource["diffs"] = $$createField5_0($$parsedSource["diffs"]);
        }
        return new I18nNewKeysReport(/** @type {Partial<I18nNewKeysReport>} */($$parsedSource));
    }
}

/**
 * LangKeyDiff 单个语言的键差异
 */
export class LangKeyDiff {
    /**
     * Creates a new LangKeyDiff instance.
     * @param {Partial<LangKeyDiff>} [$$source = {}] - The source object to create the LangKeyDiff.
     */
    constructor($$source = {}) {
        if (!("lang_code" in $$source)) {
            /**
             * 如 zh-CN / en-US
             * @member
             * @type {string}
             */
            this["lang_code"] = "";
        }
        if (!("lang_native" in $$source)) {
            /**
             * 该语言的 lang.name 翻译，用于 UI 展示
             * @member
             * @type {string}
             */
            this["lang_native"] = "";
        }
        if (!("new_keys" in $$source)) {
            /**
             * 内嵌比用户多出来的键（用户缺失，需要补全）
             * @member
             * @type {string[]}
             */
            this["new_keys"] = [];
        }
        if (!("changed_keys" in $$source)) {
            /**
             * 两边都有但内嵌新版本值不同的键
             * @member
             * @type {string[]}
             */
            this["changed_keys"] = [];
        }
        if (!("obsolete_keys" in $$source)) {
            /**
             * 用户有但内嵌没有的键（冗余/旧版残留，可选清理）
             * @member
             * @type {string[]}
             */
            this["obsolete_keys"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LangKeyDiff instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LangKeyDiff}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("new_keys" in $$parsedSource) {
            $$parsedSource["new_keys"] = $$createField2_0($$parsedSource["new_keys"]);
        }
        if ("changed_keys" in $$parsedSource) {
            $$parsedSource["changed_keys"] = $$createField3_0($$parsedSource["changed_keys"]);
        }
        if ("obsolete_keys" in $$parsedSource) {
            $$parsedSource["obsolete_keys"] = $$createField4_0($$parsedSource["obsolete_keys"]);
        }
        return new LangKeyDiff(/** @type {Partial<LangKeyDiff>} */($$parsedSource));
    }
}

/**
 * PickedFile 文件选择/读取的统一返回结构（用于编辑弹窗的封面/歌词导入）
 */
export class PickedFile {
    /**
     * Creates a new PickedFile instance.
     * @param {Partial<PickedFile>} [$$source = {}] - The source object to create the PickedFile.
     */
    constructor($$source = {}) {
        if (!("data" in $$source)) {
            /**
             * base64 编码的文件数据（图片用）
             * @member
             * @type {string}
             */
            this["data"] = "";
        }
        if (!("mime" in $$source)) {
            /**
             * MIME 类型
             * @member
             * @type {string}
             */
            this["mime"] = "";
        }
        if (!("text" in $$source)) {
            /**
             * 文本内容（歌词用）
             * @member
             * @type {string}
             */
            this["text"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PickedFile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PickedFile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PickedFile(/** @type {Partial<PickedFile>} */($$parsedSource));
    }
}

export class PlayerState {
    /**
     * Creates a new PlayerState instance.
     * @param {Partial<PlayerState>} [$$source = {}] - The source object to create the PlayerState.
     */
    constructor($$source = {}) {
        if (!("track" in $$source)) {
            /**
             * @member
             * @type {format$0.MscData | null}
             */
            this["track"] = null;
        }
        if (!("isPlaying" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isPlaying"] = false;
        }
        if (!("position" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["position"] = 0;
        }
        if (!("duration" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration"] = 0;
        }
        if (!("volume" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["volume"] = 0;
        }
        if (!("playMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["playMode"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PlayerState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PlayerState}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("track" in $$parsedSource) {
            $$parsedSource["track"] = $$createField0_0($$parsedSource["track"]);
        }
        return new PlayerState(/** @type {Partial<PlayerState>} */($$parsedSource));
    }
}

/**
 * QueueItem 队列项：曲目完整数据 + 原始位置（用于拖拽 UI）
 */
export class QueueItem {
    /**
     * Creates a new QueueItem instance.
     * @param {Partial<QueueItem>} [$$source = {}] - The source object to create the QueueItem.
     */
    constructor($$source = {}) {
        if (!("track" in $$source)) {
            /**
             * @member
             * @type {format$0.MscData}
             */
            this["track"] = (new format$0.MscData());
        }
        if (!("source" in $$source)) {
            /**
             * 入队时的原始下标（UI 排序辅助，可选）
             * @member
             * @type {number}
             */
            this["source"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueueItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QueueItem}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("track" in $$parsedSource) {
            $$parsedSource["track"] = $$createField0_0($$parsedSource["track"]);
        }
        return new QueueItem(/** @type {Partial<QueueItem>} */($$parsedSource));
    }
}

/**
 * QueueStatus 暴露给前端的队列快照
 */
export class QueueStatus {
    /**
     * Creates a new QueueStatus instance.
     * @param {Partial<QueueStatus>} [$$source = {}] - The source object to create the QueueStatus.
     */
    constructor($$source = {}) {
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {QueueItem[]}
             */
            this["items"] = [];
        }
        if (!("currentIndex" in $$source)) {
            /**
             * 当前播放项在队列中的下标，-1 表示不在队列中
             * @member
             * @type {number}
             */
            this["currentIndex"] = 0;
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueueStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QueueStatus}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new QueueStatus(/** @type {Partial<QueueStatus>} */($$parsedSource));
    }
}

/**
 * Settings 应用设置结构体
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * "dark" | "light" | "accent" | "custom"
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("player_font" in $$source)) {
            /**
             * 播放器字体
             * @member
             * @type {string}
             */
            this["player_font"] = "";
        }
        if (!("lyrics_font" in $$source)) {
            /**
             * 歌词字体
             * @member
             * @type {string}
             */
            this["lyrics_font"] = "";
        }
        if (!("ui_scale" in $$source)) {
            /**
             * 界面缩放比例 (20-500)，默认 100
             * @member
             * @type {number}
             */
            this["ui_scale"] = 0;
        }
        if (!("lyrics_scale" in $$source)) {
            /**
             * 歌词缩放比例 (20-500)，默认 100
             * @member
             * @type {number}
             */
            this["lyrics_scale"] = 0;
        }
        if (!("last_track_id" in $$source)) {
            /**
             * 上次播放的曲目ID
             * @member
             * @type {number}
             */
            this["last_track_id"] = 0;
        }
        if (!("last_position" in $$source)) {
            /**
             * 上次播放位置（秒）
             * @member
             * @type {number}
             */
            this["last_position"] = 0;
        }
        if (!("volume" in $$source)) {
            /**
             * 音量 0-100
             * @member
             * @type {number}
             */
            this["volume"] = 0;
        }
        if (!("accent_color" in $$source)) {
            /**
             * 自定义主题色（十六进制，如 #1DB954）
             * @member
             * @type {string}
             */
            this["accent_color"] = "";
        }
        if (!("language" in $$source)) {
            /**
             * 界面语言："zh-CN" | "en"
             * @member
             * @type {string}
             */
            this["language"] = "";
        }
        if (!("lyric_animation" in $$source)) {
            /**
             * 全屏歌词切换动画："fade" | "slide-up" | "slide-left" | "zoom" | "none"
             * @member
             * @type {string}
             */
            this["lyric_animation"] = "";
        }
        if (!("list_mode" in $$source)) {
            /**
             * 音乐库列表模式："card" | "list"
             * @member
             * @type {string}
             */
            this["list_mode"] = "";
        }
        if (!("animation_level" in $$source)) {
            /**
             * 界面动画级别：0=无 1=基础 2=增强(默认) 3=华丽
             * @member
             * @type {number}
             */
            this["animation_level"] = 0;
        }
        if (!("volume_mode" in $$source)) {
            /**
             * 音量模式："synth"（合成器，默认）| "master"（系统主音量）
             * @member
             * @type {string}
             */
            this["volume_mode"] = "";
        }
        if (!("max_lyric_lines" in $$source)) {
            /**
             * 同一时间戳最多允许同时显示歌词行数（1-10，默认1）
             * @member
             * @type {number}
             */
            this["max_lyric_lines"] = 0;
        }
        if (!("sort_mode" in $$source)) {
            /**
             * 音乐库排序方式："recent"（默认）| "title" | "artist"
             * @member
             * @type {string}
             */
            this["sort_mode"] = "";
        }
        if (!("bg_type" in $$source)) {
            /**
             * 背景（全页面生效：图片或视频）
             * "none" | "image" | "video"
             * @member
             * @type {string}
             */
            this["bg_type"] = "";
        }
        if (!("bg_url" in $$source)) {
            /**
             * 图片为 dataURL；视频为本地绝对文件路径（file:// 或纯路径）
             * @member
             * @type {string}
             */
            this["bg_url"] = "";
        }
        if (!("bg_fit" in $$source)) {
            /**
             * "cover" 铺满全屏 | "contain" 完整显示 | "fill" 拉伸填满 | "none" 原尺寸居中 | "scaledown" 智能缩放
             * @member
             * @type {string}
             */
            this["bg_fit"] = "";
        }
        if (!("bg_opacity" in $$source)) {
            /**
             * 背景不透明度 0-1，默认 0.9
             * @member
             * @type {number}
             */
            this["bg_opacity"] = 0;
        }
        if (!("bg_overlay" in $$source)) {
            /**
             * 前景遮罩（暗/浅色）强度 0-1，默认 0.2（提高文字对比度）
             * @member
             * @type {number}
             */
            this["bg_overlay"] = 0;
        }
        if (!("bg_blur" in $$source)) {
            /**
             * 背景模糊程度 0-30（像素），默认 0
             * @member
             * @type {number}
             */
            this["bg_blur"] = 0;
        }
        if (!("bg_loop" in $$source)) {
            /**
             * 视频是否循环（默认 true）
             * @member
             * @type {boolean}
             */
            this["bg_loop"] = false;
        }
        if (!("bg_muted" in $$source)) {
            /**
             * 视频是否静音（默认 true，推荐开启避免干扰）
             * @member
             * @type {boolean}
             */
            this["bg_muted"] = false;
        }
        if (!("bg_glass_disabled" in $$source)) {
            /**
             * 有背景时关闭所有容器毛玻璃（backdrop-filter）效果，避免边界与撕裂
             * @member
             * @type {boolean}
             */
            this["bg_glass_disabled"] = false;
        }
        if (!("window_alpha" in $$source)) {
            /**
             * 整窗透明度 0.01-1.0，默认 1；对桌面透出实现 Aero 效果
             * @member
             * @type {number}
             */
            this["window_alpha"] = 0;
        }
        if (!("aero_blur" in $$source)) {
            /**
             * Aero 透明模式下的背景模糊量（px，0-40，默认 0）；0=关闭模糊
             * @member
             * @type {number}
             */
            this["aero_blur"] = 0;
        }
        if (!("player_bg_blur" in $$source)) {
            /**
             * 播放器封面背景模糊量（px，0-30，默认 20）；作用于新/旧 UI 的 .player-bg-layer
             * @member
             * @type {number}
             */
            this["player_bg_blur"] = 0;
        }
        if (!("design_radius" in $$source)) {
            /**
             * 设计令牌（设计器实时调整，持久化到 settings.json）
             * 圆角（px，0-28，默认 10）
             * @member
             * @type {number}
             */
            this["design_radius"] = 0;
        }
        if (!("design_blur" in $$source)) {
            /**
             * 毛玻璃模糊量（px，0-40，默认 16）
             * @member
             * @type {number}
             */
            this["design_blur"] = 0;
        }
        if (!("design_anim_mult" in $$source)) {
            /**
             * 动画速度倍率（0.3-2.5，默认 1.0）
             * @member
             * @type {number}
             */
            this["design_anim_mult"] = 0;
        }
        if (!("design_shadow" in $$source)) {
            /**
             * 浮层阴影强度（0-1，默认 0.45）
             * @member
             * @type {number}
             */
            this["design_shadow"] = 0;
        }
        if (!("design_glow" in $$source)) {
            /**
             * 主题色辉光范围（0-1，默认 0.35）
             * @member
             * @type {number}
             */
            this["design_glow"] = 0;
        }
        if (!("design_text_glow" in $$source)) {
            /**
             * 字体晕影强度（0-1，默认 0）
             * @member
             * @type {number}
             */
            this["design_text_glow"] = 0;
        }
        if (!("titlebar_text" in $$source)) {
            /**
             * 自定义标题栏文字（空则使用默认 "MusicLite Cuckoo"）
             * @member
             * @type {string}
             */
            this["titlebar_text"] = "";
        }
        if (!("settings_layout" in $$source)) {
            /**
             * 设置界面布局与新 UI
             * 设置界面布局："scroll"（默认）| "columns" | "tabs"
             * @member
             * @type {string}
             */
            this["settings_layout"] = "";
        }
        if (!("new_ui_enabled" in $$source)) {
            /**
             * 新风格 UI 开关
             * @member
             * @type {boolean}
             */
            this["new_ui_enabled"] = false;
        }
        if (!("void_mode" in $$source)) {
            /**
             * 虚空模式：界面颠倒 + 全黑 + 鼠标手电筒（需自行寻找退出按钮）
             * @member
             * @type {boolean}
             */
            this["void_mode"] = false;
        }
        if (!("hotkey_playpause" in $$source)) {
            /**
             * 全局快捷键（3 个）
             * 播放 / 暂停切换
             * @member
             * @type {HotkeyConfig}
             */
            this["hotkey_playpause"] = (new HotkeyConfig());
        }
        if (!("hotkey_next" in $$source)) {
            /**
             * 下一曲
             * @member
             * @type {HotkeyConfig}
             */
            this["hotkey_next"] = (new HotkeyConfig());
        }
        if (!("hotkey_prev" in $$source)) {
            /**
             * 上一曲
             * @member
             * @type {HotkeyConfig}
             */
            this["hotkey_prev"] = (new HotkeyConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        const $$createField38_0 = $$createType9;
        const $$createField39_0 = $$createType9;
        const $$createField40_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("hotkey_playpause" in $$parsedSource) {
            $$parsedSource["hotkey_playpause"] = $$createField38_0($$parsedSource["hotkey_playpause"]);
        }
        if ("hotkey_next" in $$parsedSource) {
            $$parsedSource["hotkey_next"] = $$createField39_0($$parsedSource["hotkey_next"]);
        }
        if ("hotkey_prev" in $$parsedSource) {
            $$parsedSource["hotkey_prev"] = $$createField40_0($$parsedSource["hotkey_prev"]);
        }
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

/**
 * GetTrayState 返回托盘菜单需要的状态（当前曲目名、是否播放中、封面Base64），供前端自定义菜单渲染
 */
export class TrayState {
    /**
     * Creates a new TrayState instance.
     * @param {Partial<TrayState>} [$$source = {}] - The source object to create the TrayState.
     */
    constructor($$source = {}) {
        if (!("trackName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["trackName"] = "";
        }
        if (!("artistName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artistName"] = "";
        }
        if (!("isPlaying" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isPlaying"] = false;
        }
        if (!("coverBase64" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["coverBase64"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TrayState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TrayState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TrayState(/** @type {Partial<TrayState>} */($$parsedSource));
    }
}

/**
 * UpdateInfo 检查更新返回结构
 */
export class UpdateInfo {
    /**
     * Creates a new UpdateInfo instance.
     * @param {Partial<UpdateInfo>} [$$source = {}] - The source object to create the UpdateInfo.
     */
    constructor($$source = {}) {
        if (!("hasUpdate" in $$source)) {
            /**
             * 是否有新版本
             * @member
             * @type {boolean}
             */
            this["hasUpdate"] = false;
        }
        if (!("currentVer" in $$source)) {
            /**
             * 当前版本（已剥离 -dev 后缀）
             * @member
             * @type {string}
             */
            this["currentVer"] = "";
        }
        if (!("latestVer" in $$source)) {
            /**
             * 最新版本
             * @member
             * @type {string}
             */
            this["latestVer"] = "";
        }
        if (!("latestTag" in $$source)) {
            /**
             * 最新版本 tag（如 Beta0.7.1）
             * @member
             * @type {string}
             */
            this["latestTag"] = "";
        }
        if (!("releaseTitle" in $$source)) {
            /**
             * Release 标题
             * @member
             * @type {string}
             */
            this["releaseTitle"] = "";
        }
        if (!("releaseNotes" in $$source)) {
            /**
             * Release notes（markdown 原文）
             * @member
             * @type {string}
             */
            this["releaseNotes"] = "";
        }
        if (!("releaseURL" in $$source)) {
            /**
             * Release 网页地址
             * @member
             * @type {string}
             */
            this["releaseURL"] = "";
        }
        if (!("downloadURL" in $$source)) {
            /**
             * 当前平台的便携包下载地址（无则空）
             * @member
             * @type {string}
             */
            this["downloadURL"] = "";
        }
        if (!("downloadName" in $$source)) {
            /**
             * 下载文件名（展示用）
             * @member
             * @type {string}
             */
            this["downloadName"] = "";
        }
        if (!("downloadSize" in $$source)) {
            /**
             * 下载字节数
             * @member
             * @type {number}
             */
            this["downloadSize"] = 0;
        }
        if (!("publishedAt" in $$source)) {
            /**
             * 发布时间 RFC3339
             * @member
             * @type {string}
             */
            this["publishedAt"] = "";
        }
        if (!("platform" in $$source)) {
            /**
             * 当前平台（windows/darwin/linux）
             * @member
             * @type {string}
             */
            this["platform"] = "";
        }
        if (!("isPrerelease" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isPrerelease"] = false;
        }
        if (!("error" in $$source)) {
            /**
             * 检查失败时的错误信息
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo(/** @type {Partial<UpdateInfo>} */($$parsedSource));
    }
}

/**
 * VersionInfo 供前端 bindings 直接消费的结构
 */
export class VersionInfo {
    /**
     * Creates a new VersionInfo instance.
     * @param {Partial<VersionInfo>} [$$source = {}] - The source object to create the VersionInfo.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("buildSha" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["buildSha"] = "";
        }
        if (!("buildNum" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["buildNum"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VersionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VersionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VersionInfo(/** @type {Partial<VersionInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = LangKeyDiff.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = format$0.MscData.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = QueueItem.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = HotkeyConfig.createFrom;
