// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MusicService 主服务结构体（v3 Service 模式）
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as format$0 from "../internal/format/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as storage$0 from "../internal/storage/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteTrack 删除曲目
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteTrack(id) {
    return $Call.ByID(808260112, id);
}

/**
 * EmitEvent 封装 v3 事件发送，供 Player 等内部组件调用
 * @param {string} name
 * @param {any[]} data
 * @returns {$CancellablePromise<void>}
 */
export function EmitEvent(name, ...data) {
    return $Call.ByID(3264670627, name, data);
}

/**
 * ExportSettings 导出当前设置为 .msclte.zip 文件
 * 包含 settings.json + 当前所用字体的 base64 编码数据
 * @returns {$CancellablePromise<string>}
 */
export function ExportSettings() {
    return $Call.ByID(1325937017);
}

/**
 * GetAllTracks 返回所有曲目列表（前端列表页用）
 * @returns {$CancellablePromise<format$0.MscData[]>}
 */
export function GetAllTracks() {
    return $Call.ByID(2221140177).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetApplicationVolume 获取应用音量（synth 模式：读取 Windows 音量合成器中本进程的音量）
 * @returns {$CancellablePromise<number>}
 */
export function GetApplicationVolume() {
    return $Call.ByID(371764106);
}

/**
 * GetDatabase 暴露数据库实例给 AudioHandler 使用（生产模式用）
 * @returns {$CancellablePromise<storage$0.Database | null>}
 */
export function GetDatabase() {
    return $Call.ByID(1326684263).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<format$0.MscData>}
 */
export function GetFileInArgs() {
    return $Call.ByID(2280569798).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetI18nData 暴露给前端：返回完整翻译数据
 * @returns {$CancellablePromise<$models.I18nData>}
 */
export function GetI18nData() {
    return $Call.ByID(2121690250).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetInstalledFonts 返回系统中安装的字体名称列表（去重、排序）
 * - Windows: 读注册表 HKLM/HKCU\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts
 * - macOS:   fc-list 或 ~/Library/Fonts 等目录
 * - Linux:   fc-list 或 ~/.local/share/fonts、/usr/share/fonts 等目录
 * 平台分派由 fonts_windows.go / fonts_notwindows.go 中的 readInstalledFonts 提供
 * @returns {$CancellablePromise<string[]>}
 */
export function GetInstalledFonts() {
    return $Call.ByID(2346987914).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetListenTime 获取某首歌的累计听歌时长（秒）
 * @param {number} trackId
 * @returns {$CancellablePromise<number>}
 */
export function GetListenTime(trackId) {
    return $Call.ByID(2859168132, trackId);
}

/**
 * GetNextTracks 返回下一曲目（前端用）
 * @param {number} currTrackId
 * @returns {$CancellablePromise<format$0.MscData>}
 */
export function GetNextTracks(currTrackId) {
    return $Call.ByID(3284356975, currTrackId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {number} currTrackId
 * @returns {$CancellablePromise<format$0.MscData>}
 */
export function GetPrevTracks(currTrackId) {
    return $Call.ByID(384409383, currTrackId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {number} currTrackId
 * @returns {$CancellablePromise<format$0.MscData>}
 */
export function GetRandomTrack(currTrackId) {
    return $Call.ByID(3034848620, currTrackId).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetSystemMasterVolume 获取系统主音量 (0-100)
 * @returns {$CancellablePromise<number>}
 */
export function GetSystemMasterVolume() {
    return $Call.ByID(3305262859);
}

/**
 * GetTotalListenTime 获取所有歌曲的总听歌时长（秒）
 * @returns {$CancellablePromise<number>}
 */
export function GetTotalListenTime() {
    return $Call.ByID(4250614846);
}

/**
 * GetTrack 返回单首曲目完整数据（播放器页用）
 * @param {number} id
 * @returns {$CancellablePromise<format$0.MscData>}
 */
export function GetTrack(id) {
    return $Call.ByID(577520329, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetTrayState 暴露给前端：拉取当前托盘状态
 * @returns {$CancellablePromise<$models.TrayState>}
 */
export function GetTrayState() {
    return $Call.ByID(2404781643).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * HideMainWindow 暴露给前端：关闭按钮 → 隐藏到托盘（而非退出）
 * @returns {$CancellablePromise<void>}
 */
export function HideMainWindow() {
    return $Call.ByID(80267543);
}

/**
 * HideTrayMenu 暴露给前端：关闭自绘托盘菜单窗口（前端 Esc / 点击外部 / blur 等都可调用）
 * @returns {$CancellablePromise<void>}
 */
export function HideTrayMenu() {
    return $Call.ByID(1743593797);
}

/**
 * HotkeyApply 更新后端快捷键配置（Wails 绑定，前端保存设置时调用）
 * @returns {$CancellablePromise<void>}
 */
export function HotkeyApply() {
    return $Call.ByID(1166990868);
}

/**
 * HotkeyFormatKey 格式化快捷键显示文本（Wails 绑定，前端用于显示）
 * @param {string} keys
 * @returns {$CancellablePromise<string>}
 */
export function HotkeyFormatKey(keys) {
    return $Call.ByID(4165578266, keys);
}

/**
 * HotkeyGetActionList 返回支持的快捷键动作列表（前端用于生成 UI）
 * @returns {$CancellablePromise<{ [_ in string]?: string }[]>}
 */
export function HotkeyGetActionList() {
    return $Call.ByID(1573858682).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * HotkeyGetConfig 返回当前快捷键配置
 * @returns {$CancellablePromise<{ [_ in string]?: $models.HotkeyConfig }>}
 */
export function HotkeyGetConfig() {
    return $Call.ByID(549795818).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * HotkeyParseFromJS 从前端的 keydown 事件数据解析快捷键字符串
 * 前端传入的格式: {ctrl: true, shift: false, alt: false, meta: false, key: "p"}
 * @param {boolean} ctrl
 * @param {boolean} shift
 * @param {boolean} alt
 * @param {boolean} meta
 * @param {string} key
 * @returns {$CancellablePromise<string>}
 */
export function HotkeyParseFromJS(ctrl, shift, alt, meta, key) {
    return $Call.ByID(1146801992, ctrl, shift, alt, meta, key);
}

/**
 * ImportFiles 打开多选对话框导入音频文件，返回成功导入的数量
 * @returns {$CancellablePromise<number>}
 */
export function ImportFiles() {
    return $Call.ByID(4110489706);
}

/**
 * ImportFilesFromPaths 按文件路径批量导入（拖放场景用）
 * @param {string[]} paths
 * @returns {$CancellablePromise<number>}
 */
export function ImportFilesFromPaths(paths) {
    return $Call.ByID(2311333378, paths);
}

/**
 * ImportSettings 从 .msclte.zip 文件导入设置
 * 返回导入后的新设置，前端可直接应用
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function ImportSettings() {
    return $Call.ByID(2398840366).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * IsDefaultPlayer 检查 MusicLite 是否为 .mp3 的默认播放器（Windows 实现）
 * @returns {$CancellablePromise<boolean>}
 */
export function IsDefaultPlayer() {
    return $Call.ByID(1169550414);
}

/**
 * IsTrayQuitting 返回托盘退出标志（供 main.go 窗口关闭钩子检查）
 * @returns {$CancellablePromise<boolean>}
 */
export function IsTrayQuitting() {
    return $Call.ByID(557340885);
}

/**
 * LoadSettings 加载设置（文件不存在则返回默认设置）
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function LoadSettings() {
    return $Call.ByID(1006476059).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * MuteSystemMasterVolume 静音系统
 * @returns {$CancellablePromise<void>}
 */
export function MuteSystemMasterVolume() {
    return $Call.ByID(1630954678);
}

/**
 * OpenAppDataFolder 在系统文件管理器中打开程序数据文件夹（%APPDATA%/MusicLite）
 * @returns {$CancellablePromise<void>}
 */
export function OpenAppDataFolder() {
    return $Call.ByID(1785754749);
}

/**
 * OpenGitHubRepo 在系统默认浏览器中打开项目 GitHub 仓库页面
 * @returns {$CancellablePromise<void>}
 */
export function OpenGitHubRepo() {
    return $Call.ByID(1460875157);
}

/**
 * OpenSettingsWindow 暴露给前端：从托盘菜单 / 主界面打开设置窗口
 * @returns {$CancellablePromise<void>}
 */
export function OpenSettingsWindow() {
    return $Call.ByID(3661599939);
}

/**
 * PackShare 打包分享：读取曲目音频，写入封面和歌词标签，复制到剪贴板
 * 剪贴板写入逻辑按平台分派：
 *   - Windows:   CF_HDROP (share_windows.go)
 *   - macOS:     AppleScript + NSPasteboard (share_notwindows.go)
 *   - Linux:     xclip / wl-copy (share_notwindows.go)
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function PackShare(id) {
    return $Call.ByID(988473870, id);
}

/**
 * PickImageFile 打开文件对话框选择图片，读取并返回 base64 数据 + MIME
 * @returns {$CancellablePromise<$models.PickedFile>}
 */
export function PickImageFile() {
    return $Call.ByID(1908735394).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * PickLyricsFile 打开文件对话框选择歌词文件，读取并返回文本内容
 * @returns {$CancellablePromise<string>}
 */
export function PickLyricsFile() {
    return $Call.ByID(271904085);
}

/**
 * EqBandCount 常量前端不可见，前端通过 PlayerGetEqBandCount 获取
 * PlayerGetEqBandCount 返回频段数量
 * @returns {$CancellablePromise<number>}
 */
export function PlayerGetEqBandCount() {
    return $Call.ByID(3596696711);
}

/**
 * PlayerGetEqEnabled 返回均衡器启用状态
 * @returns {$CancellablePromise<boolean>}
 */
export function PlayerGetEqEnabled() {
    return $Call.ByID(1249190876);
}

/**
 * PlayerGetEqFreqs 返回各频段中心频率（Hz）
 * @returns {$CancellablePromise<number[]>}
 */
export function PlayerGetEqFreqs() {
    return $Call.ByID(276610990).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * PlayerGetEqGains 返回当前各频段增益（dB）
 * @returns {$CancellablePromise<number[]>}
 */
export function PlayerGetEqGains() {
    return $Call.ByID(1596937225).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * PlayerGetPlayMode 返回当前播放模式
 * @returns {$CancellablePromise<string>}
 */
export function PlayerGetPlayMode() {
    return $Call.ByID(2555362128);
}

/**
 * PlayerGetSmartEQEnabled 返回智能均衡器启用状态
 * @returns {$CancellablePromise<boolean>}
 */
export function PlayerGetSmartEQEnabled() {
    return $Call.ByID(476461161);
}

/**
 * PlayerGetSmartEQIntensity 返回智能均衡器补偿强度
 * @returns {$CancellablePromise<number>}
 */
export function PlayerGetSmartEQIntensity() {
    return $Call.ByID(1479599449);
}

/**
 * PlayerGetState 返回当前播放器状态快照
 * @returns {$CancellablePromise<$models.PlayerState>}
 */
export function PlayerGetState() {
    return $Call.ByID(427269906).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * PlayerLoad 加载并准备播放一首曲目（加载后处于暂停态，需调用 PlayerPlay 开始）
 * @param {format$0.MscData} track
 * @returns {$CancellablePromise<void>}
 */
export function PlayerLoad(track) {
    return $Call.ByID(3003710095, track);
}

/**
 * PlayerPause 暂停播放
 * @returns {$CancellablePromise<void>}
 */
export function PlayerPause() {
    return $Call.ByID(2048929159);
}

/**
 * PlayerPlay 恢复播放
 * @returns {$CancellablePromise<void>}
 */
export function PlayerPlay() {
    return $Call.ByID(1372849669);
}

/**
 * PlayerResetEq 重置全部频段为 0 dB（不平路状态，仍保持启用/旁路）
 * @returns {$CancellablePromise<void>}
 */
export function PlayerResetEq() {
    return $Call.ByID(3589013128);
}

/**
 * PlayerRestart 从头重新播放当前曲目（前端在 loopOne 之外需要时可用）
 * @returns {$CancellablePromise<void>}
 */
export function PlayerRestart() {
    return $Call.ByID(1056890142);
}

/**
 * PlayerSeek 跳转到指定秒数
 * @param {number} seconds
 * @returns {$CancellablePromise<void>}
 */
export function PlayerSeek(seconds) {
    return $Call.ByID(2166882483, seconds);
}

/**
 * PlayerSetEqBand 设置某频段增益（dB，-12~+12）
 * @param {number} index
 * @param {number} gainDB
 * @returns {$CancellablePromise<void>}
 */
export function PlayerSetEqBand(index, gainDB) {
    return $Call.ByID(2988181052, index, gainDB);
}

/**
 * PlayerSetEqEnabled 启用/旁路均衡器
 * @param {boolean} on
 * @returns {$CancellablePromise<void>}
 */
export function PlayerSetEqEnabled(on) {
    return $Call.ByID(872630704, on);
}

/**
 * PlayerSetEqGains 一次性设置全部频段增益（长度须等于频段数）
 * @param {number[]} gains
 * @returns {$CancellablePromise<void>}
 */
export function PlayerSetEqGains(gains) {
    return $Call.ByID(3358137941, gains);
}

/**
 * PlayerSetSmartEQEnabled 启用/旁路智能均衡器
 * @param {boolean} on
 * @returns {$CancellablePromise<void>}
 */
export function PlayerSetSmartEQEnabled(on) {
    return $Call.ByID(3264969045, on);
}

/**
 * PlayerSetSmartEQIntensity 设置智能均衡器补偿强度（0-1）
 * @param {number} v
 * @returns {$CancellablePromise<void>}
 */
export function PlayerSetSmartEQIntensity(v) {
    return $Call.ByID(4125904613, v);
}

/**
 * PlayerStop 停止并清空当前曲目
 * @returns {$CancellablePromise<void>}
 */
export function PlayerStop() {
    return $Call.ByID(4085131727);
}

/**
 * PlayerToggle 切换播放/暂停
 * @returns {$CancellablePromise<void>}
 */
export function PlayerToggle() {
    return $Call.ByID(1605585451);
}

/**
 * PlayerTogglePlayMode 切换播放模式并返回新模式
 * @returns {$CancellablePromise<string>}
 */
export function PlayerTogglePlayMode() {
    return $Call.ByID(3240042494);
}

/**
 * QueueAddAll 批量加入队列
 * @param {number[]} ids
 * @returns {$CancellablePromise<number>}
 */
export function QueueAddAll(ids) {
    return $Call.ByID(83489555, ids);
}

/**
 * QueueAddAllFromLibrary 把整个音乐库加入队列（"播放全部"用）
 * @returns {$CancellablePromise<number>}
 */
export function QueueAddAllFromLibrary() {
    return $Call.ByID(1068977170);
}

/**
 * QueueAddTrack 按曲目 ID 加入队列尾部，返回加入的项（失败返回空项）
 * @param {number} id
 * @returns {$CancellablePromise<$models.QueueItem>}
 */
export function QueueAddTrack(id) {
    return $Call.ByID(68181639, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * QueueClear 清空队列
 * @returns {$CancellablePromise<void>}
 */
export function QueueClear() {
    return $Call.ByID(684955182);
}

/**
 * QueueGetNext 取下一项（不前进指针），用于前端手动"下一首"决策；无则返回空项
 * @returns {$CancellablePromise<$models.QueueItem>}
 */
export function QueueGetNext() {
    return $Call.ByID(2031574098).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * QueueGetPrev 取上一项；无则返回空项
 * @returns {$CancellablePromise<$models.QueueItem>}
 */
export function QueueGetPrev() {
    return $Call.ByID(3949423462).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * QueueGetStatus 返回队列快照
 * @returns {$CancellablePromise<$models.QueueStatus>}
 */
export function QueueGetStatus() {
    return $Call.ByID(2959569805).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * QueueJumpTo 跳转到指定下标并播放该项
 * @param {number} index
 * @returns {$CancellablePromise<void>}
 */
export function QueueJumpTo(index) {
    return $Call.ByID(2830091184, index);
}

/**
 * QueueMove 拖拽排序：from → to
 * @param {number} $from
 * @param {number} to
 * @returns {$CancellablePromise<boolean>}
 */
export function QueueMove($from, to) {
    return $Call.ByID(3266569048, $from, to);
}

/**
 * QueueRemoveAt 删除指定下标的队列项
 * @param {number} index
 * @returns {$CancellablePromise<boolean>}
 */
export function QueueRemoveAt(index) {
    return $Call.ByID(695921764, index);
}

/**
 * QueueShuffle 洗牌（保留当前播放项位置）
 * @returns {$CancellablePromise<void>}
 */
export function QueueShuffle() {
    return $Call.ByID(2680245010);
}

/**
 * QuitApp 暴露给前端：从自定义菜单触发退出（设置 trayQuitting 以便窗口关闭钩子放行）
 * @returns {$CancellablePromise<void>}
 */
export function QuitApp() {
    return $Call.ByID(379397228);
}

/**
 * ReadFileForEdit 根据路径读取文件（拖放场景），自动检测类型并填充对应字段
 * @param {string} path
 * @returns {$CancellablePromise<$models.PickedFile>}
 */
export function ReadFileForEdit(path) {
    return $Call.ByID(3392836227, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * RecordPlayPause 计算本次播放时长并累积到 pending
 * @param {number} trackId
 * @returns {$CancellablePromise<void>}
 */
export function RecordPlayPause(trackId) {
    return $Call.ByID(2813746305, trackId);
}

/**
 * RecordPlayStart 记录某首歌开始播放的时间（内存中）
 * @param {number} trackId
 * @returns {$CancellablePromise<void>}
 */
export function RecordPlayStart(trackId) {
    return $Call.ByID(3237840323, trackId);
}

/**
 * ResetSettings 返回默认设置（不立即写盘，由前端再次调用 SaveSettings 持久化）
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function ResetSettings() {
    return $Call.ByID(2661309004).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * SaveSettings 保存设置
 * @param {$models.Settings} s
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(s) {
    return $Call.ByID(1391045782, s);
}

/**
 * SetApplicationVolume 设置应用音量（synth 模式：控制 Windows 音量合成器中本进程的音量）
 * 播放迁移到 Go 后端后，音频由 Go 进程直接输出，音量合成器里的会话 PID 就是本进程自身，
 * 因此用 os.Getpid() 匹配音频会话即可命中。同时同步更新后端 Player 的 beep 增益，
 * 让两者保持一致（合成器滑块是主控，beep 增益作为应用内二次校准）。
 * @param {number} vol
 * @returns {$CancellablePromise<void>}
 */
export function SetApplicationVolume(vol) {
    return $Call.ByID(2355041038, vol);
}

/**
 * SetAsDefaultPlayer 将 MusicLite 设为支持音频格式的默认播放器（Windows 实现）
 * @returns {$CancellablePromise<void>}
 */
export function SetAsDefaultPlayer() {
    return $Call.ByID(2888466302);
}

/**
 * SetSystemMasterVolume 设置系统主音量 (0-100)
 * 由 itchyny/volume-go 跨平台实现：
 *   - Windows: 走 Core Audio / MMDevice API
 *   - macOS:   走 AppleScript / CoreAudio
 *   - Linux:   走 amixer (ALSA) / pactl (PulseAudio)
 * @param {number} vol
 * @returns {$CancellablePromise<void>}
 */
export function SetSystemMasterVolume(vol) {
    return $Call.ByID(870203751, vol);
}

/**
 * ShowMainWindow 暴露给前端：从自定义菜单中打开主窗口
 * @returns {$CancellablePromise<void>}
 */
export function ShowMainWindow() {
    return $Call.ByID(4154600878);
}

/**
 * TogglePlayPause 暴露给前端：自定义托盘菜单中切换播放/暂停
 * @returns {$CancellablePromise<void>}
 */
export function TogglePlayPause() {
    return $Call.ByID(1696574922);
}

/**
 * UnmuteSystemMasterVolume 取消静音
 * @returns {$CancellablePromise<void>}
 */
export function UnmuteSystemMasterVolume() {
    return $Call.ByID(3753703197);
}

/**
 * UpdateTrack 更新曲目基本信息（标题、艺术家、歌词）
 * @param {number} id
 * @param {string} title
 * @param {string} artist
 * @param {string} lyrics
 * @returns {$CancellablePromise<void>}
 */
export function UpdateTrack(id, title, artist, lyrics) {
    return $Call.ByID(2216425542, id, title, artist, lyrics);
}

/**
 * UpdateTrackCover 更新曲目封面
 * @param {number} id
 * @param {string} coverData
 * @param {string} coverMIME
 * @returns {$CancellablePromise<void>}
 */
export function UpdateTrackCover(id, coverData, coverMIME) {
    return $Call.ByID(3333748965, id, coverData, coverMIME);
}

// Private type creation functions
const $$createType0 = format$0.MscData.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = storage$0.Database.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $models.I18nData.createFrom;
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = $models.TrayState.createFrom;
const $$createType7 = $Create.Map($Create.Any, $Create.Any);
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $models.HotkeyConfig.createFrom;
const $$createType10 = $Create.Map($Create.Any, $$createType9);
const $$createType11 = $models.Settings.createFrom;
const $$createType12 = $models.PickedFile.createFrom;
const $$createType13 = $Create.Array($Create.Any);
const $$createType14 = $models.PlayerState.createFrom;
const $$createType15 = $models.QueueItem.createFrom;
const $$createType16 = $models.QueueStatus.createFrom;
