// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class MscData {
    /**
     * Creates a new MscData instance.
     * @param {Partial<MscData>} [$$source = {}] - The source object to create the MscData.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * 曲目ID
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * 曲名
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("artist" in $$source)) {
            /**
             * 艺术家/作曲家
             * @member
             * @type {string}
             */
            this["artist"] = "";
        }
        if (!("album" in $$source)) {
            /**
             * 专辑
             * @member
             * @type {string}
             */
            this["album"] = "";
        }
        if (!("format" in $$source)) {
            /**
             * 格式
             * @member
             * @type {NormalMscFormat}
             */
            this["format"] = NormalMscFormat.$zero;
        }
        if (!("src" in $$source)) {
            /**
             * 音频URI (/audio/<id>)
             * @member
             * @type {string}
             */
            this["src"] = "";
        }
        if (!("cover" in $$source)) {
            /**
             * 封面URI (/cover/<id>)
             * @member
             * @type {string}
             */
            this["cover"] = "";
        }
        if (!("lyrics" in $$source)) {
            /**
             * 歌词
             * @member
             * @type {string}
             */
            this["lyrics"] = "";
        }
        if (!("importedAt" in $$source)) {
            /**
             * 入库时间戳（Unix 秒），供前端排序用
             * @member
             * @type {number}
             */
            this["importedAt"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MscData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MscData}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MscData(/** @type {Partial<MscData>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const NormalMscFormat = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    Mp3: "mp3",
    Wav: "wav",
    Flac: "flac",
    Ogg: "ogg",
    APE: "ape",
};
