// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTrack(arg1) {
  return window['go']['main']['App']['DeleteTrack'](arg1);
}

export function ExportSettings() {
  return window['go']['main']['App']['ExportSettings']();
}

export function GetAllTracks() {
  return window['go']['main']['App']['GetAllTracks']();
}

export function GetApplicationVolume() {
  return window['go']['main']['App']['GetApplicationVolume']();
}

export function GetDatabase() {
  return window['go']['main']['App']['GetDatabase']();
}

export function GetFileInArgs() {
  return window['go']['main']['App']['GetFileInArgs']();
}

export function GetI18nData() {
  return window['go']['main']['App']['GetI18nData']();
}

export function GetInstalledFonts() {
  return window['go']['main']['App']['GetInstalledFonts']();
}

export function GetListenTime(arg1) {
  return window['go']['main']['App']['GetListenTime'](arg1);
}

export function GetNextTracks(arg1) {
  return window['go']['main']['App']['GetNextTracks'](arg1);
}

export function GetPrevTracks(arg1) {
  return window['go']['main']['App']['GetPrevTracks'](arg1);
}

export function GetRandomTrack(arg1) {
  return window['go']['main']['App']['GetRandomTrack'](arg1);
}

export function GetSystemMasterVolume() {
  return window['go']['main']['App']['GetSystemMasterVolume']();
}

export function GetTotalListenTime() {
  return window['go']['main']['App']['GetTotalListenTime']();
}

export function GetTrack(arg1) {
  return window['go']['main']['App']['GetTrack'](arg1);
}

export function HotkeyApply() {
  return window['go']['main']['App']['HotkeyApply']();
}

export function HotkeyFormatKey(arg1) {
  return window['go']['main']['App']['HotkeyFormatKey'](arg1);
}

export function HotkeyGetActionList() {
  return window['go']['main']['App']['HotkeyGetActionList']();
}

export function HotkeyGetConfig() {
  return window['go']['main']['App']['HotkeyGetConfig']();
}

export function HotkeyParseFromJS(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['HotkeyParseFromJS'](arg1, arg2, arg3, arg4, arg5);
}

export function ImportFiles() {
  return window['go']['main']['App']['ImportFiles']();
}

export function ImportFilesFromPaths(arg1) {
  return window['go']['main']['App']['ImportFilesFromPaths'](arg1);
}

export function ImportSettings() {
  return window['go']['main']['App']['ImportSettings']();
}

export function IsDefaultPlayer() {
  return window['go']['main']['App']['IsDefaultPlayer']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function MuteSystemMasterVolume() {
  return window['go']['main']['App']['MuteSystemMasterVolume']();
}

export function OpenAppDataFolder() {
  return window['go']['main']['App']['OpenAppDataFolder']();
}

export function PackShare(arg1) {
  return window['go']['main']['App']['PackShare'](arg1);
}

export function PickImageFile() {
  return window['go']['main']['App']['PickImageFile']();
}

export function PickLyricsFile() {
  return window['go']['main']['App']['PickLyricsFile']();
}

export function PlayerGetEqBandCount() {
  return window['go']['main']['App']['PlayerGetEqBandCount']();
}

export function PlayerGetEqEnabled() {
  return window['go']['main']['App']['PlayerGetEqEnabled']();
}

export function PlayerGetEqFreqs() {
  return window['go']['main']['App']['PlayerGetEqFreqs']();
}

export function PlayerGetEqGains() {
  return window['go']['main']['App']['PlayerGetEqGains']();
}

export function PlayerGetPlayMode() {
  return window['go']['main']['App']['PlayerGetPlayMode']();
}

export function PlayerGetSmartEQEnabled() {
  return window['go']['main']['App']['PlayerGetSmartEQEnabled']();
}

export function PlayerGetSmartEQIntensity() {
  return window['go']['main']['App']['PlayerGetSmartEQIntensity']();
}

export function PlayerGetState() {
  return window['go']['main']['App']['PlayerGetState']();
}

export function PlayerLoad(arg1) {
  return window['go']['main']['App']['PlayerLoad'](arg1);
}

export function PlayerPause() {
  return window['go']['main']['App']['PlayerPause']();
}

export function PlayerPlay() {
  return window['go']['main']['App']['PlayerPlay']();
}

export function PlayerResetEq() {
  return window['go']['main']['App']['PlayerResetEq']();
}

export function PlayerRestart() {
  return window['go']['main']['App']['PlayerRestart']();
}

export function PlayerSeek(arg1) {
  return window['go']['main']['App']['PlayerSeek'](arg1);
}

export function PlayerSetEqBand(arg1, arg2) {
  return window['go']['main']['App']['PlayerSetEqBand'](arg1, arg2);
}

export function PlayerSetEqEnabled(arg1) {
  return window['go']['main']['App']['PlayerSetEqEnabled'](arg1);
}

export function PlayerSetEqGains(arg1) {
  return window['go']['main']['App']['PlayerSetEqGains'](arg1);
}

export function PlayerSetSmartEQEnabled(arg1) {
  return window['go']['main']['App']['PlayerSetSmartEQEnabled'](arg1);
}

export function PlayerSetSmartEQIntensity(arg1) {
  return window['go']['main']['App']['PlayerSetSmartEQIntensity'](arg1);
}

export function PlayerStop() {
  return window['go']['main']['App']['PlayerStop']();
}

export function PlayerToggle() {
  return window['go']['main']['App']['PlayerToggle']();
}

export function PlayerTogglePlayMode() {
  return window['go']['main']['App']['PlayerTogglePlayMode']();
}

export function QueueAddAll(arg1) {
  return window['go']['main']['App']['QueueAddAll'](arg1);
}

export function QueueAddAllFromLibrary() {
  return window['go']['main']['App']['QueueAddAllFromLibrary']();
}

export function QueueAddTrack(arg1) {
  return window['go']['main']['App']['QueueAddTrack'](arg1);
}

export function QueueClear() {
  return window['go']['main']['App']['QueueClear']();
}

export function QueueGetNext() {
  return window['go']['main']['App']['QueueGetNext']();
}

export function QueueGetPrev() {
  return window['go']['main']['App']['QueueGetPrev']();
}

export function QueueGetStatus() {
  return window['go']['main']['App']['QueueGetStatus']();
}

export function QueueJumpTo(arg1) {
  return window['go']['main']['App']['QueueJumpTo'](arg1);
}

export function QueueMove(arg1, arg2) {
  return window['go']['main']['App']['QueueMove'](arg1, arg2);
}

export function QueueRemoveAt(arg1) {
  return window['go']['main']['App']['QueueRemoveAt'](arg1);
}

export function QueueShuffle() {
  return window['go']['main']['App']['QueueShuffle']();
}

export function ReadFileForEdit(arg1) {
  return window['go']['main']['App']['ReadFileForEdit'](arg1);
}

export function RecordPlayPause(arg1) {
  return window['go']['main']['App']['RecordPlayPause'](arg1);
}

export function RecordPlayStart(arg1) {
  return window['go']['main']['App']['RecordPlayStart'](arg1);
}

export function ResetSettings() {
  return window['go']['main']['App']['ResetSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetApplicationVolume(arg1) {
  return window['go']['main']['App']['SetApplicationVolume'](arg1);
}

export function SetAsDefaultPlayer() {
  return window['go']['main']['App']['SetAsDefaultPlayer']();
}

export function SetSystemMasterVolume(arg1) {
  return window['go']['main']['App']['SetSystemMasterVolume'](arg1);
}

export function UnmuteSystemMasterVolume() {
  return window['go']['main']['App']['UnmuteSystemMasterVolume']();
}

export function UpdateTrack(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateTrack'](arg1, arg2, arg3, arg4);
}

export function UpdateTrackCover(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTrackCover'](arg1, arg2, arg3);
}
