// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {format} from '../models';
import {storage} from '../models';
import {main} from '../models';

export function DeleteTrack(arg1:number):Promise<void>;

export function ExportSettings():Promise<string>;

export function GetAllTracks():Promise<Array<format.MscData>>;

export function GetApplicationVolume():Promise<number>;

export function GetDatabase():Promise<storage.Database>;

export function GetFileInArgs():Promise<format.MscData>;

export function GetI18nData():Promise<main.I18nData>;

export function GetInstalledFonts():Promise<Array<string>>;

export function GetListenTime(arg1:number):Promise<number>;

export function GetNextTracks(arg1:number):Promise<format.MscData>;

export function GetPrevTracks(arg1:number):Promise<format.MscData>;

export function GetRandomTrack(arg1:number):Promise<format.MscData>;

export function GetTotalListenTime():Promise<number>;

export function GetTrack(arg1:number):Promise<format.MscData>;

export function ImportFiles():Promise<number>;

export function ImportFilesFromPaths(arg1:Array<string>):Promise<number>;

export function ImportSettings():Promise<main.Settings>;

export function LoadSettings():Promise<main.Settings>;

export function OpenAppDataFolder():Promise<void>;

export function RecordPlayPause(arg1:number):Promise<void>;

export function RecordPlayStart(arg1:number):Promise<void>;

export function ResetSettings():Promise<main.Settings>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SetApplicationVolume(arg1:number):Promise<void>;

export function UpdateTrack(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateTrackCover(arg1:number,arg2:Array<number>,arg3:string):Promise<void>;
