// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTrack(arg1) {
  return window['go']['main']['App']['DeleteTrack'](arg1);
}

export function GetAllTracks() {
  return window['go']['main']['App']['GetAllTracks']();
}

export function GetDatabase() {
  return window['go']['main']['App']['GetDatabase']();
}

export function GetFileInArgs() {
  return window['go']['main']['App']['GetFileInArgs']();
}

export function GetInstalledFonts() {
  return window['go']['main']['App']['GetInstalledFonts']();
}

export function GetNextTracks(arg1) {
  return window['go']['main']['App']['GetNextTracks'](arg1);
}

export function GetRandomTrack(arg1) {
  return window['go']['main']['App']['GetRandomTrack'](arg1);
}

export function GetTrack(arg1) {
  return window['go']['main']['App']['GetTrack'](arg1);
}

export function ImportFiles() {
  return window['go']['main']['App']['ImportFiles']();
}

export function ImportFilesFromPaths(arg1) {
  return window['go']['main']['App']['ImportFilesFromPaths'](arg1);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function UpdateTrack(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateTrack'](arg1, arg2, arg3, arg4);
}

export function UpdateTrackCover(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTrackCover'](arg1, arg2, arg3);
}
