// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {format} from '../models';
import {storage} from '../models';
import {main} from '../models';

export function DeleteTrack(arg1:number):Promise<void>;

export function ExportSettings():Promise<string>;

export function GetAllTracks():Promise<Array<format.MscData>>;

export function GetApplicationVolume():Promise<number>;

export function GetDatabase():Promise<storage.Database>;

export function GetFileInArgs():Promise<format.MscData>;

export function GetI18nData():Promise<main.I18nData>;

export function GetInstalledFonts():Promise<Array<string>>;

export function GetListenTime(arg1:number):Promise<number>;

export function GetNextTracks(arg1:number):Promise<format.MscData>;

export function GetPrevTracks(arg1:number):Promise<format.MscData>;

export function GetRandomTrack(arg1:number):Promise<format.MscData>;

export function GetSystemMasterVolume():Promise<number>;

export function GetTotalListenTime():Promise<number>;

export function GetTrack(arg1:number):Promise<format.MscData>;

export function HotkeyApply():Promise<void>;

export function HotkeyFormatKey(arg1:string):Promise<string>;

export function HotkeyGetActionList():Promise<Array<Record<string, string>>>;

export function HotkeyGetConfig():Promise<Record<string, main.HotkeyConfig>>;

export function HotkeyParseFromJS(arg1:boolean,arg2:boolean,arg3:boolean,arg4:boolean,arg5:string):Promise<string>;

export function ImportFiles():Promise<number>;

export function ImportFilesFromPaths(arg1:Array<string>):Promise<number>;

export function ImportSettings():Promise<main.Settings>;

export function IsDefaultPlayer():Promise<boolean>;

export function LoadSettings():Promise<main.Settings>;

export function MuteSystemMasterVolume():Promise<void>;

export function OpenAppDataFolder():Promise<void>;

export function PackShare(arg1:number):Promise<void>;

export function PickImageFile():Promise<main.PickedFile>;

export function PickLyricsFile():Promise<string>;

export function PlayerGetEqBandCount():Promise<number>;

export function PlayerGetEqEnabled():Promise<boolean>;

export function PlayerGetEqFreqs():Promise<Array<number>>;

export function PlayerGetEqGains():Promise<Array<number>>;

export function PlayerGetPlayMode():Promise<string>;

export function PlayerGetSmartEQEnabled():Promise<boolean>;

export function PlayerGetSmartEQIntensity():Promise<number>;

export function PlayerGetState():Promise<main.PlayerState>;

export function PlayerLoad(arg1:format.MscData):Promise<void>;

export function PlayerPause():Promise<void>;

export function PlayerPlay():Promise<void>;

export function PlayerResetEq():Promise<void>;

export function PlayerRestart():Promise<void>;

export function PlayerSeek(arg1:number):Promise<void>;

export function PlayerSetEqBand(arg1:number,arg2:number):Promise<void>;

export function PlayerSetEqEnabled(arg1:boolean):Promise<void>;

export function PlayerSetEqGains(arg1:Array<number>):Promise<void>;

export function PlayerSetSmartEQEnabled(arg1:boolean):Promise<void>;

export function PlayerSetSmartEQIntensity(arg1:number):Promise<void>;

export function PlayerStop():Promise<void>;

export function PlayerToggle():Promise<void>;

export function PlayerTogglePlayMode():Promise<string>;

export function QueueAddAll(arg1:Array<number>):Promise<number>;

export function QueueAddAllFromLibrary():Promise<number>;

export function QueueAddTrack(arg1:number):Promise<main.QueueItem>;

export function QueueClear():Promise<void>;

export function QueueGetNext():Promise<main.QueueItem>;

export function QueueGetPrev():Promise<main.QueueItem>;

export function QueueGetStatus():Promise<main.QueueStatus>;

export function QueueJumpTo(arg1:number):Promise<void>;

export function QueueMove(arg1:number,arg2:number):Promise<boolean>;

export function QueueRemoveAt(arg1:number):Promise<boolean>;

export function QueueShuffle():Promise<void>;

export function ReadFileForEdit(arg1:string):Promise<main.PickedFile>;

export function RecordPlayPause(arg1:number):Promise<void>;

export function RecordPlayStart(arg1:number):Promise<void>;

export function ResetSettings():Promise<main.Settings>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SetApplicationVolume(arg1:number):Promise<void>;

export function SetAsDefaultPlayer():Promise<void>;

export function SetSystemMasterVolume(arg1:number):Promise<void>;

export function UnmuteSystemMasterVolume():Promise<void>;

export function UpdateTrack(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateTrackCover(arg1:number,arg2:Array<number>,arg3:string):Promise<void>;
