// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTrack(arg1) {
  return window['go']['main']['App']['DeleteTrack'](arg1);
}

export function ExportSettings() {
  return window['go']['main']['App']['ExportSettings']();
}

export function GetAllTracks() {
  return window['go']['main']['App']['GetAllTracks']();
}

export function GetApplicationVolume() {
  return window['go']['main']['App']['GetApplicationVolume']();
}

export function GetDatabase() {
  return window['go']['main']['App']['GetDatabase']();
}

export function GetFileInArgs() {
  return window['go']['main']['App']['GetFileInArgs']();
}

export function GetI18nData() {
  return window['go']['main']['App']['GetI18nData']();
}

export function GetInstalledFonts() {
  return window['go']['main']['App']['GetInstalledFonts']();
}

export function GetListenTime(arg1) {
  return window['go']['main']['App']['GetListenTime'](arg1);
}

export function GetNextTracks(arg1) {
  return window['go']['main']['App']['GetNextTracks'](arg1);
}

export function GetPrevTracks(arg1) {
  return window['go']['main']['App']['GetPrevTracks'](arg1);
}

export function GetRandomTrack(arg1) {
  return window['go']['main']['App']['GetRandomTrack'](arg1);
}

export function GetTotalListenTime() {
  return window['go']['main']['App']['GetTotalListenTime']();
}

export function GetTrack(arg1) {
  return window['go']['main']['App']['GetTrack'](arg1);
}

export function ImportFiles() {
  return window['go']['main']['App']['ImportFiles']();
}

export function ImportFilesFromPaths(arg1) {
  return window['go']['main']['App']['ImportFilesFromPaths'](arg1);
}

export function ImportSettings() {
  return window['go']['main']['App']['ImportSettings']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function OpenAppDataFolder() {
  return window['go']['main']['App']['OpenAppDataFolder']();
}

export function PackShare(arg1) {
  return window['go']['main']['App']['PackShare'](arg1);
}

export function PickImageFile() {
  return window['go']['main']['App']['PickImageFile']();
}

export function PickLyricsFile() {
  return window['go']['main']['App']['PickLyricsFile']();
}

export function ReadFileForEdit(arg1) {
  return window['go']['main']['App']['ReadFileForEdit'](arg1);
}

export function RecordPlayPause(arg1) {
  return window['go']['main']['App']['RecordPlayPause'](arg1);
}

export function RecordPlayStart(arg1) {
  return window['go']['main']['App']['RecordPlayStart'](arg1);
}

export function ResetSettings() {
  return window['go']['main']['App']['ResetSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SetApplicationVolume(arg1) {
  return window['go']['main']['App']['SetApplicationVolume'](arg1);
}

export function UpdateTrack(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateTrack'](arg1, arg2, arg3, arg4);
}

export function UpdateTrackCover(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTrackCover'](arg1, arg2, arg3);
}
