// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {format} from '../models';
import {storage} from '../models';
import {main} from '../models';

export function DeleteTrack(arg1:number):Promise<void>;

export function GetAllTracks():Promise<Array<format.MscData>>;

export function GetDatabase():Promise<storage.Database>;

export function GetTrack(arg1:number):Promise<format.MscData>;

export function ImportFiles():Promise<number>;

export function LoadSettings():Promise<main.Settings>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function UpdateTrack(arg1:number,arg2:string,arg3:string,arg4:string):Promise<void>;

export function UpdateTrackCover(arg1:number,arg2:Array<number>,arg3:string):Promise<void>;
